deployment:
  tasks:
    - export DEPLOYPATH=/home/abdiadam/repositories/abdi-adama-frontend
    # Delete default cPanel and Sitejet junk files
    - /bin/rm -f $DEPLOYPATH/default.php $DEPLOYPATH/default.html $DEPLOYPATH/index.php
    # Deploy frontend static files to the target directory
    - /bin/cp -R dist/* $DEPLOYPATH
    # Deploy .htaccess for HTTPS enforcement
    - /bin/cp .htaccess $DEPLOYPATH/.htaccess
    
    # 2. Deploy Backend Silo
    - /bin/mkdir -p $DEPLOYPATH/backend-core-silo
    - /bin/cp -R backend-core-silo/* $DEPLOYPATH/backend-core-silo/