-- Privileged-account seeding was intentionally removed from automatic
-- migrations. Run `npm run seed:superadmin` with the documented SEED_* runtime
-- environment variables when bootstrapping a new, trusted database.
